$primary_paletteKeyColor = 1AFF5C
$secondary_paletteKeyColor = 1AFF5C
$tertiary_paletteKeyColor = 1AFF5C
$neutral_paletteKeyColor = 000000
$neutral_variant_paletteKeyColor = 003D14
$background = 000000
$onBackground = 1AFF5C
$surface = 000000
$surfaceDim = 000000
$surfaceBright = 003D14
$surfaceContainerLowest = 000000
$surfaceContainerLow = 001707
$surfaceContainer = 00220B
$surfaceContainerHigh = 002E0F
$surfaceContainerHighest = 003D14
$onSurface = 1AFF5C
$surfaceVariant = 003D14
$onSurfaceVariant = 1AFF5C
$inverseSurface = 1AFF5C
$inverseOnSurface = 000000
$outline = 1AFF5C
$outlineVariant = 005A1F
$shadow = 000000
$scrim = 000000
$surfaceTint = 1AFF5C
$primary = 1AFF5C
$onPrimary = 000000
$primaryContainer = 003D14
$onPrimaryContainer = 1AFF5C
$inversePrimary = 1AFF5C
$secondary = 1AFF5C
$onSecondary = 000000
$secondaryContainer = 003D14
$onSecondaryContainer = 1AFF5C
$tertiary = 1AFF5C
$onTertiary = 000000
$tertiaryContainer = 003D14
$onTertiaryContainer = 1AFF5C
$error = FF0033
$onError = 000000
$errorContainer = 220000
$onErrorContainer = FF3355
$primaryFixed = 1AFF5C
$primaryFixedDim = 1AFF5C
$onPrimaryFixed = 000000
$onPrimaryFixedVariant = 003D14
$secondaryFixed = 1AFF5C
$secondaryFixedDim = 1AFF5C
$onSecondaryFixed = 000000
$onSecondaryFixedVariant = 003D14
$tertiaryFixed = 1AFF5C
$tertiaryFixedDim = 1AFF5C
$onTertiaryFixed = 000000
$onTertiaryFixedVariant = 003D14
$term0 = 000000
$term1 = FF0033
$term2 = 1AFF5C
$term3 = 1AFF5C
$term4 = 1AFF5C
$term5 = 1AFF5C
$term6 = 1AFF5C
$term7 = 1AFF5C
$term8 = 003D14
$term9 = FF3355
$term10 = 1AFF5C
$term11 = 1AFF5C
$term12 = 1AFF5C
$term13 = 1AFF5C
$term14 = 1AFF5C
$term15 = DFFFDF
$rosewater = 1AFF5C
$flamingo = 1AFF5C
$pink = 1AFF5C
$mauve = 1AFF5C
$red = FF0033
$maroon = FF3355
$peach = 1AFF5C
$yellow = 1AFF5C
$green = 1AFF5C
$teal = 1AFF5C
$sky = 1AFF5C
$sapphire = 1AFF5C
$blue = 1AFF5C
$lavender = 1AFF5C
$klink = 1AFF5C
$klinkSelection = 1AFF5C
$kvisited = 1AFF5C
$kvisitedSelection = 1AFF5C
$knegative = FF0033
$knegativeSelection = FF3355
$kneutral = 1AFF5C
$kneutralSelection = 1AFF5C
$kpositive = 1AFF5C
$kpositiveSelection = 1AFF5C
$text = 1AFF5C
$subtext1 = 0FCC4A
$subtext0 = 0A9938
$overlay2 = 005A1F
$overlay1 = 004718
$overlay0 = 003D14
$surface2 = 002E0F
$surface1 = 00220B
$surface0 = 001707
$base = 000000
$mantle = 000000
$crust = 000000
$success = 1AFF5C
$onSuccess = 000000
$successContainer = 003D14
$onSuccessContainer = 1AFF5C
